# Generated by Django 4.0.4 on 2022-06-15 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_avatar_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_set",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="following_set",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="20px * 20px 크기의 파일을 업로드해주세요",
                upload_to="accounts/avatar//%Y/%m/%d",
            ),
        ),
    ]
