# Generated by Django 4.0.4 on 2022-06-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"verbose_name_plural": "USER"},
        ),
    ]
